### ISSUE TITLE
unhandled exception and math throws a 0 instead of the correct answer when answered

### ISSUE THREAD

**Issue by Evauation** [Terraria-Builders-Community/Prizes#1]
![image](https://user-images.githubusercontent.com/108847709/208731475-27b1a62f-81b8-46d0-91ff-82aaf0e36f97.png)

self-explanatory, it pretty much threw an error when answered correctly and the math problem answered will throw a 0 in chat instead of the correct answer.

**Comment by RenderBr** [comment]
fixed.

**Comment by Evauation** [comment]
another tiny issue 

if you get /answer wrong, it will just say Something went wrong!

**Comment by RenderBr** [comment]
> another tiny issue
> 
> if you get /answer wrong, it will just say Something went wrong!

fixed
